.TH FEDORA-L10N 1 "February 2026" "fedora-l10n" "User Commands"
.SH NAME
fedora-l10n \- Fedora Linux translation status viewer
.SH SYNOPSIS
.B fedora-l10n
.SH DESCRIPTION
A GTK4/Libadwaita application for viewing Fedora Linux translation progress.
.SH AUTHOR
Daniel Nylander <daniel@danielnylander.se>
